default: &default
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  host: "localhost"
  username: name
  password: passwd

development:
  <<: *default
  database: peneira_development

test:
  <<: *default
  database: peneira_test

production:
  <<: *default
  database: peneira_production
  username: peneira
  password: <%= ENV['PENEIRA_DATABASE_PASSWORD'] %>
