# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6537d73b2d5feda422b8b88d2fbbb99ae32f1ae68e619bdeb1b2dab7aacb4ddfea10145c31e69973f226ad936f0060a73c3b0bf57b8f1cc1c702402b72341542

test:
  secret_key_base: cfeb2153876cebe46fde4875a8fa2d713cbb32056d06bad1f9ec70f2a375e1f4c566f8e97fbb06a5f2201ab37b5ea7254f475af0a6075c547cb81a4c99495709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
